CREATE DATABASE Company;
USE Company;
CREATE TABLE DEPARTMENT (
DeptID VARCHAR(50) PRIMARY KEY,
DeptName VARCHAR(50) DEFAULT "Employee"
);
CREATE TABLE EMPLOYEE (
EmpID VARCHAR(50) PRIMARY KEY,
EmpName VARCHAR(50) NOT NULL,
Email VARCHAR(50) UNIQUE,
Salary INT CHECK(Salary > 10000),
DeptID VARCHAR(50),
FOREIGN KEY (DeptID) REFERENCES DEPARTMENT (DeptID)
);
SHOW TABLES;
DESCRIBE DEPARTMENT;
DESCRIBE EMPLOYEE;
DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;

