create database Company;
drop database Company;
use Company;
create table DEPARTMENT (
DNAME VARCHAR(50) NOT NULL,
DNUMBER INT PRIMARY KEY,
MGRSSN VARCHAR(50) unique,
MGRSTARTDATE date
);
create table EMPLOYEE (
FNAME VARCHAR(50) NOT NULL,
MNAME VARCHAR(50) NOT NULL,
LNAME VARCHAR(50) NOT NULL,
SSN VARCHAR(50) PRIMARY KEY,
BDATE DATE default(1/1/2001),
ADDRESS VARCHAR(50) NOT NULL,
SEX VARCHAR(50),
SALARY DECIMAL(10,2) CHECK(SALARY > 10000),
SUPERSSN VARCHAR(50),
foreign key (SUPERSSN) references EMPLOYEE(SSN),
DNO INT,
foreign key(DNO) references DEPARTMENT(DNUMBER)
); 

CREATE TABLE DEPT_LOCATIONS (
DNUMBER INT PRIMARY KEY,
foreign key(DNUMBER) references DEPARTMENT(DNUMBER),
DLOCATION VARCHAR(50)
);

CREATE TABLE PROJECT (
PNAME VARCHAR(50) NOT NULL,
PNUMBER INT PRIMARY KEY,
PLOCTATION VARCHAR(50),
DNUM INT,
foreign key(DNUM) references DEPARTMENT(DNUMBER)
);

CREATE TABLE WORKS_ON (
ESSN VARCHAR(50),
foreign key(ESSN) references DEPARTMENT(DNUMBER),
PNO INT,
FOREIGN KEY(PNO) REFERENCES PROJECT(PNUMBER),
HOURS INT
);

CREATE TABLE DEPENDENT (
ESSN VARCHAR(50),
foreign key(ESSN) references EMPLOYEE(SSN),
DEPENDENT_NAME VARCHAR(50),
SEX VARCHAR(50),
BDATE DATE NOT NULL,
RELATIONSHIP VARCHAR(50)
);
ALTER TABLE DEPARTMENT
ADD CONSTRAINT Employee_SSN
FOREIGN KEY (MGRSSN)
REFERENCES EMPLOYEE(SSN);





